version: '3.8'

services:
  marketing-post-generator:
    build:
      context: .
      target: production
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - MCP_MODE=remote
      - MCP_PORT=3000
      - POSTGEN_DATA_DIR=/data/.postgen
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - postgen-data:/data/.postgen
      - logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mcp-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Development service
  marketing-post-generator-dev:
    build:
      context: .
      target: builder
    ports:
      - "${DEV_PORT:-3001}:3000"
    environment:
      - NODE_ENV=development
      - MCP_MODE=local
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
      - postgen-data:/data/.postgen
    command: npm run dev
    networks:
      - mcp-network
    profiles:
      - development

volumes:
  postgen-data:
    driver: local
  logs:
    driver: local

networks:
  mcp-network:
    driver: bridge